### ISSUE TITLE
sources are automatically goes non-operational

### ISSUE THREAD

**Issue by bachig26** [JorrinKievit/restreamer#10]
## Summary

as you can see in the screenshots, a lot of the sources are `non-operational`, and when i click the `Refetch`, some shows as operational but it doesn't work/ show while playing a video and after when click the `settings` to the status of the sources, it becomes as `non-operational`.

### Screenshot

| ![Restreamer_3SBxBfxSpd](https://github.com/JorrinKievit/restreamer/assets/96393348/0b4b3eb1-f05d-450d-8528-e9738b0b928f) | ![Restreamer_DfC0tK9MRk](https://github.com/JorrinKievit/restreamer/assets/96393348/840ced69-8e4f-41aa-b54a-cc75e94e1cb3) |
| :----: | :----: |

**Comment by JorrinKievit** [comment]
Ye the sources can be inconsistent. In the settings, the sources are tested against a single movie (Avengers Infinity War in this case). So it really depends on what you are watching whether a source works or not. Often sources also randomly break, which is out of my control obviously 😄
