### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by zisra** [JorrinKievit/restreamer#17]
Is it possible to create a macOS build for both silicon and intel?

**Comment by JorrinKievit** [comment]
I think i tried this before quite a while ago when i still had a MacBook. But i couldn't install apps that weren't code signed. To code sign, you need a developer license, which costs i think $100 a year which is not worth it to me 😝 . Maybe it is possible somehow but i dont have a macbook anymore so i cant test it 🙁

**Comment by zisra** [comment]
@JorrinKievit there's a workaround for installing unsigned apps, plenty of open source developers use it: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by JorrinKievit** [comment]
I can include the builds in the next version and we'll see if they work 🙂

**Comment by JorrinKievit** [comment]
Added in the new release @zisra
