### ISSUE TITLE
just use movie-web.app tbh

### ISSUE THREAD

**Issue by castdrian** [JorrinKievit/restreamer#8]
see title

**Comment by JorrinKievit** [comment]
Didnt even exist when I started this project. Its also just a fun hobby project for me, if I wanted to just wanted to watch shows i could do that at a 1000 other places

**Comment by zisra** [comment]
@JorrinKievit We have a package over at https://github.com/movie-web/providers. It has good [docs](https://providers.docs.movie-web.app/) too, would you be interested in using it? We would also be very happy to add providers from this repo so there is no loss of providers. Thank you! 😄

**Comment by JorrinKievit** [comment]
@zisra Hiya! I could make some PR's to add the providers that are in here. When we got enough providers I could port them over to in here. I think at this point we started copying stuff from both repos (no offense, open source for a reason 😄 ) which seems counter productive. What do you think?

**Comment by zisra** [comment]
@JorrinKievit sounds great, I can help port some more providers over as well! Just let me know which ones and I can take care of some
