### ISSUE TITLE
Need help !

### ISSUE THREAD

**Issue by IrfanKhan66** [JorrinKievit/restreamer#9]
## Trying to scrape video providers but facing cors and cloudflare blocked errors

I learnt many things from your scraping logic and tried to implement some of the provider's scarping logic in my private api, but I'm facing errors like cors and cloudflare 403, for eg. while requesting smashystream's fizzzz1.php server I faced 403 cloudflare error, and while requsting the hash froim vidsrc.me with its v2 rcp url I got the 404 error always.

*Note  :* Im using node js with axios and cheerio, and for cors error I used corsproxy.io but then also got blocked

sorry of contacting you like this I'm new to this and didnt find your email to contact you.

**Comment by JorrinKievit** [comment]
I think all of those errors are because the URLs require a "referer" header

**Comment by IrfanKhan66** [comment]
I used the referer but then also, it would be better if you try it in a
sandbox heres the link : axios sandbox
<https://codesandbox.io/s/ecstatic-williams-5v47sl?file=/src/App.js>

**Comment by JorrinKievit** [comment]
Full code to get the url and subtitles:
```
async function getEms(url) {
  const res = await axios.get(url, {
    headers: {
      referer: url,
    },
  });
  const config = JSON.parse(
    res.data.match(/new\s+Playerjs\((\{[^]*?\})\);/)[1].replace(/'/g, '"')
  );
  const fileUrl = config.file;
  const subtitleArray = config.subtitle
    .split(",")
    .map((entry) => {
      const nameRegex = /\[([^\]]*)\]/;
      const urlRegex = /(https:\/\/[^\s,]+)/;
      const nameMatch = nameRegex.exec(entry);
      const urlMatch = urlRegex.exec(entry);
      const name =
        nameMatch && nameMatch[1].trim()
          ? nameMatch[1].trim()
          : urlMatch && urlMatch[1];
      const url = urlMatch && urlMatch[0].trim();
      return { name, url };
    })
    .filter((subtitle) => subtitle.name !== null);
  console.log(fileUrl, subtitleArray);
}

getEms(
  "https://embed.smashystream.com/ems.php?imdb=tt2306299&season=1&episode=1"
);
```

**Comment by JorrinKievit** [comment]
Also btw you should read about doing requests from the browser, and why you can't do requests from the browser with headers like referer.

**Comment by IrfanKhan66** [comment]
@JorrinKievit thanks for your help I just tried to request it again now it works fine, can't say what was the issue but I will look forward to implement proxy rotation logic to prevent the risk of getting blocked, any suggesstions how I should do it ?

**Comment by JorrinKievit** [comment]
I have no idea 😄

**Comment by IrfanKhan66** [comment]
@JorrinKievit I don't want to annoy you but do you know why its getting 404 error, - `import { load } from "cheerio";
import client from "../helpers/client";

const url: string = "https://vidsrc.me/";
const rcpUrl: string = "https://rcp.vidsrc.me/rcp/";
const rcpHls: string = "https://v2.vidsrc.me/srcrcp/";
const referer: string = "https://vidsrc.me/";
const referer2: string = "https://vidsrc.stream/";
const embedUrl: string = `${url}/embed/`;

const vidsrc = async (id: number | string) => {
  if (!id) return "No id provided !";
  let hash: string = "";

  try {
    const data = await client(`${embedUrl}${id}`);
    if (!data) return console.error("No data found !");
    const $ = load(data);

    const firstHash = $("#sources div.source").first().attr("data-hash");
    hash = firstHash;
  } catch (err) {
    console.error(err.message);
  }

  // console.log(hash, rcpHls+hash)
  // if (!hash) return console.error("No hash found !");

  // console.log(rcpHls+hash)
  let hlsData: string;
  try {
    hlsData = await client(rcpHls + hash, {
      Referer: rcpHls + hash,
      "User-Agent":
        "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0",
    });
  } catch (err) {
    console.error(err.message);
  }

  console.log(hlsData);
  // if (!hlsData) return console.error("Error calling v2 rcp !");

  // const matchHls = hlsData.match(/\/g)
};

export default vidsrc;
`

**Comment by IrfanKhan66** [comment]
> I have no idea 😄

ohk no problem , thanks for your help !
